<?php
class Docket_extra_field_table extends MX_Controller
{
    public function column_list()
    {
        $column_structure = array(
            0 => 'Field:id, Type:int(11), Null:NO, Key:PRI, Default:, Extra:auto_increment',
            1 => 'Field:status, Type:tinyint(1), Null:NO, Key:, Default:1, Extra:',
            2 => 'Field:docket_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            3 => 'Field:brand_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            4 => 'Field:po_number, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            5 => 'Field:created_date, Type:datetime, Null:NO, Key:, Default:, Extra:',
            6 => 'Field:created_by, Type:int(11), Null:NO, Key:, Default:, Extra:',
            7 => 'Field:modified_date, Type:datetime, Null:NO, Key:, Default:, Extra:',
            8 => 'Field:modified_by, Type:int(11), Null:NO, Key:, Default:, Extra:',
            9 => 'Field:docket_edit_field, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            10 => 'Field:pickup_boy_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            11 => 'Field:cod_status, Type:tinyint(1), Null:NO, Key:, Default:, Extra:',
            12 => 'Field:inscan_date, Type:datetime, Null:NO, Key:, Default:, Extra:',
            13 => 'Field:paid_amount, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            14 => 'Field:balance_amount, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            15 => 'Field:sales_currency_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            16 => 'Field:purchase_currency_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            17 => 'Field:nimbuspost_sales_amt, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            18 => 'Field:nimbuspost_purchase_amt, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            19 => 'Field:entry_number, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            20 => 'Field:total_quantity, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            21 => 'Field:forwarder_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            22 => 'Field:weight_change_email_send, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            23 => 'Field:estimate_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            24 => 'Field:license_location_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            25 => 'Field:token_number, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            26 => 'Field:project_name, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            27 => 'Field:free_value1, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            28 => 'Field:free_value2, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            29 => 'Field:free_value3, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            30 => 'Field:free_value4, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            31 => 'Field:free_value5, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            32 => 'Field:free_value6, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            33 => 'Field:free_value7, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            34 => 'Field:free_text1, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            35 => 'Field:free_text2, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            36 => 'Field:free_text3, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            37 => 'Field:free_text4, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            38 => 'Field:free_text5, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            39 => 'Field:free_text6, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            40 => 'Field:free_text7, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            41 => 'Field:origin_route_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            42 => 'Field:dest_route_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            43 => 'Field:api_rate, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            44 => 'Field:api_rate_currency, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            45 => 'Field:material_content, Type:text, Null:NO, Key:, Default:, Extra:',
            46 => 'Field:vat, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            47 => 'Field:admin_charge, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            48 => 'Field:extra_charge, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            49 => 'Field:total_charges, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            50 => 'Field:cancel_shipment_data, Type:text, Null:NO, Key:, Default:, Extra:',
            51 => 'Field:is_cancelled, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            52 => 'Field:cancelled_date, Type:datetime, Null:NO, Key:, Default:, Extra:',
            53 => 'Field:cancelled_by, Type:int(11), Null:NO, Key:, Default:, Extra:',
            54 => 'Field:awb_mode_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            55 => 'Field:old_forwarding_no, Type:text, Null:NO, Key:, Default:, Extra:',
            56 => 'Field:fedex_reference_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            57 => 'Field:edited_chargeable_weight, Type:int(11), Null:YES, Key:, Default:0, Extra:',
            58 => 'Field:norsk_service_name, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            59 => 'Field:popup_selected_service, Type:tinyint(1), Null:NO, Key:, Default:, Extra:',
            60 => 'Field:api_parcel_no_generated, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            61 => 'Field:sector_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            62 => 'Field:use_own_invoice, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            63 => 'Field:own_invoice_file, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            64 => 'Field:pickup_awb_count, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            65 => 'Field:igm_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            66 => 'Field:igm_date, Type:date, Null:NO, Key:, Default:, Extra:',
            67 => 'Field:assessable_value, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            68 => 'Field:duty, Type:int(11), Null:NO, Key:, Default:, Extra:',
            69 => 'Field:be_sb_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            70 => 'Field:be_sb_date, Type:date, Null:NO, Key:, Default:, Extra:',
            71 => 'Field:fedex_ac_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            72 => 'Field:old_actual_wt, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            73 => 'Field:old_volumetric_wt, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            74 => 'Field:old_chargeable_wt, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            75 => 'Field:docket_grand_total, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            76 => 'Field:vehicle_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            77 => 'Field:dpd_service, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            78 => 'Field:bank_ad_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            79 => 'Field:pickup_request_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
        );
        return $column_structure;
    }
}
