<?php
class Manifest_table extends MX_Controller
{
    public function column_list()
    {
        $column_structure = array(
            0 => 'Field:id, Type:int(11), Null:NO, Key:PRI, Default:, Extra:auto_increment',
            1 => 'Field:status, Type:tinyint(1), Null:NO, Key:, Default:1, Extra:',
            2 => 'Field:booking_min, Type:date, Null:NO, Key:, Default:, Extra:',
            3 => 'Field:booking_max, Type:date, Null:NO, Key:, Default:, Extra:',
            4 => 'Field:manifest_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            5 => 'Field:forwarder_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            6 => 'Field:vendor_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            7 => 'Field:co_vendor_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            8 => 'Field:vendor_delivery, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            9 => 'Field:master_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            10 => 'Field:master_edi_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            11 => 'Field:manifest_date, Type:date, Null:NO, Key:, Default:, Extra:',
            12 => 'Field:manifest_time, Type:time, Null:NO, Key:, Default:, Extra:',
            13 => 'Field:run_number, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            14 => 'Field:flight_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            15 => 'Field:flight_no_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            16 => 'Field:vendor_cd_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            17 => 'Field:bags_count, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            18 => 'Field:arrival_date, Type:date, Null:NO, Key:, Default:, Extra:',
            19 => 'Field:actual_arrival_date, Type:date, Null:NO, Key:, Default:, Extra:',
            20 => 'Field:vendor_wt, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            21 => 'Field:ori_hub_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            22 => 'Field:dest_hub_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            23 => 'Field:vehicle_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            24 => 'Field:line_haul_vendor, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            25 => 'Field:total_bags_count, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            26 => 'Field:weight_total, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            27 => 'Field:awb_count, Type:int(11), Null:NO, Key:, Default:, Extra:',
            28 => 'Field:parcel_count, Type:int(11), Null:NO, Key:, Default:, Extra:',
            29 => 'Field:docket_dest_hub, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            30 => 'Field:docket_dest_city, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            31 => 'Field:docket_dest_state, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            32 => 'Field:edi_file_path, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            33 => 'Field:company_master_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            34 => 'Field:created_date, Type:datetime, Null:NO, Key:, Default:, Extra:',
            35 => 'Field:created_by, Type:int(11), Null:NO, Key:, Default:, Extra:',
            36 => 'Field:modified_date, Type:datetime, Null:NO, Key:, Default:, Extra:',
            37 => 'Field:modified_by, Type:int(11), Null:NO, Key:, Default:, Extra:',
            38 => 'Field:migration_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            39 => 'Field:mode_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            40 => 'Field:license_master_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            41 => 'Field:edi_import_file, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            42 => 'Field:manifest_comment, Type:text, Null:NO, Key:, Default:, Extra:',
            43 => 'Field:total_actual_wt, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            44 => 'Field:total_volumetric_wt, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            45 => 'Field:total_chargeable_wt, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            46 => 'Field:sales_total, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            47 => 'Field:purchase_total, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            48 => 'Field:edi_import_file_v, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            49 => 'Field:co_courier_max, Type:date, Null:NO, Key:, Default:, Extra:',
            50 => 'Field:co_courier_min, Type:date, Null:NO, Key:, Default:, Extra:',
            51 => 'Field:pur_vendor_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            52 => 'Field:pur_co_vendor_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            53 => 'Field:pur_product_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            54 => 'Field:auto_generate_no, Type:int(11), Null:NO, Key:, Default:, Extra:',
            55 => 'Field:awb_created_by, Type:int(11), Null:NO, Key:, Default:, Extra:',
            56 => 'Field:cfl_total_weight, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            57 => 'Field:cfl_total_bag, Type:int(11), Null:NO, Key:, Default:, Extra:',
            58 => 'Field:cft_entry_date, Type:date, Null:NO, Key:, Default:, Extra:',

        );
        return $column_structure;
    }
}
