<?php
class Pickup_request_detail_table extends MX_Controller
{
    public function column_list()
    {
        $column_structure = array(
            0 => 'Field:id, Type:int(11), Null:NO, Key:PRI, Default:, Extra:auto_increment',
            1 => 'Field:status, Type:tinyint(1), Null:NO, Key:, Default:1, Extra:',
            2 => 'Field:pickup_request_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            3 => 'Field:pickup_date, Type:date, Null:NO, Key:, Default:, Extra:',
            4 => 'Field:pickup_time, Type:time, Null:NO, Key:, Default:, Extra:',
            5 => 'Field:pickup_priority, Type:int(11), Null:NO, Key:, Default:, Extra:',
            6 => 'Field:commit_id, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            7 => 'Field:pieces, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            8 => 'Field:weight, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            9 => 'Field:remark, Type:text, Null:NO, Key:, Default:, Extra:',
            10 => 'Field:user_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            11 => 'Field:total_pieces, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            12 => 'Field:total_awb, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            13 => 'Field:po_number, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            14 => 'Field:estimate_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            15 => 'Field:pickup_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            16 => 'Field:pickup_add_save, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            17 => 'Field:pickup_name, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            18 => 'Field:pickup_address1, Type:text, Null:NO, Key:, Default:, Extra:',
            19 => 'Field:pickup_address2, Type:text, Null:NO, Key:, Default:, Extra:',
            20 => 'Field:pickup_address3, Type:text, Null:NO, Key:, Default:, Extra:',
            21 => 'Field:pickup_pincode, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            22 => 'Field:pickup_city, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            23 => 'Field:pickup_state, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            24 => 'Field:pickup_country, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            25 => 'Field:pickup_phone, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            26 => 'Field:pickup_email, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            27 => 'Field:pickup_gstin_type, Type:int(11), Null:NO, Key:, Default:, Extra:',
            28 => 'Field:pickup_gstin_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            29 => 'Field:pickup_origin_zone, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            30 => 'Field:consignee_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            31 => 'Field:consignee_save_address, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            32 => 'Field:consignee_name, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            33 => 'Field:consignee_address1, Type:text, Null:NO, Key:, Default:, Extra:',
            34 => 'Field:consignee_address2, Type:text, Null:NO, Key:, Default:, Extra:',
            35 => 'Field:consignee_address3, Type:text, Null:NO, Key:, Default:, Extra:',
            36 => 'Field:consignee_pincode, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            37 => 'Field:consignee_city, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            38 => 'Field:consignee_state, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            39 => 'Field:consignee_country, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            40 => 'Field:consignee_phone, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            41 => 'Field:consignee_email, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            42 => 'Field:consignee_gstin_type, Type:int(11), Null:NO, Key:, Default:, Extra:',
            43 => 'Field:consignee_gstin_no, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            44 => 'Field:consignee_dest_zone, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            45 => 'Field:pickup_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            46 => 'Field:consignee_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            47 => 'Field:vol_weight, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            48 => 'Field:amount, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            49 => 'Field:awb_received, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            50 => 'Field:pieces_received, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            51 => 'Field:created_date, Type:datetime, Null:NO, Key:, Default:, Extra:',
            52 => 'Field:created_by, Type:int(11), Null:NO, Key:, Default:, Extra:',
            53 => 'Field:modified_date, Type:datetime, Null:NO, Key:, Default:, Extra:',
            54 => 'Field:modified_by, Type:int(11), Null:NO, Key:, Default:, Extra:',
            55 => 'Field:pickup_dial_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            56 => 'Field:consignee_dial_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            57 => 'Field:migration_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            58 => 'Field:consignee_company, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            59 => 'Field:pickup_company, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            60 => 'Field:customer_text, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            61 => 'Field:company_edit, Type:tinyint(1), Null:NO, Key:, Default:, Extra:',
        );
        return $column_structure;
    }
}
