<?php
class Vendor_table extends MX_Controller
{
    public function column_list()
    {
        $column_structure = array(
            0 => 'Field:id, Type:int(11), Null:NO, Key:PRI, Default:, Extra:auto_increment',
            1 => 'Field:status, Type:tinyint(1), Null:YES, Key:, Default:1, Extra:',
            2 => 'Field:name, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            3 => 'Field:code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            4 => 'Field:address, Type:text, Null:NO, Key:, Default:, Extra:',
            5 => 'Field:tracking_head_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            6 => 'Field:chg_wt_per_item, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            7 => 'Field:round_off_chg_wt, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            8 => 'Field:is_gst_apply, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            9 => 'Field:manifest_event_drs, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            10 => 'Field:service_type, Type:tinyint(1), Null:NO, Key:, Default:, Extra:',
            11 => 'Field:gst_per, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            12 => 'Field:invoice_range_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            13 => 'Field:sac_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            14 => 'Field:mode_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            15 => 'Field:master_service_type, Type:int(11), Null:NO, Key:, Default:, Extra:',
            16 => 'Field:label_head_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            17 => 'Field:api_credentials, Type:text, Null:NO, Key:, Default:, Extra:',
            18 => 'Field:created_date, Type:datetime, Null:NO, Key:, Default:, Extra:',
            19 => 'Field:created_by, Type:int(11), Null:NO, Key:, Default:, Extra:',
            20 => 'Field:modified_date, Type:datetime, Null:NO, Key:, Default:, Extra:',
            21 => 'Field:modified_by, Type:int(11), Null:NO, Key:, Default:, Extra:',
            22 => 'Field:license_location_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            23 => 'Field:product_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            24 => 'Field:co_vendor_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            25 => 'Field:service_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            26 => 'Field:vat_per, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            27 => 'Field:max_wt_per_pc, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            28 => 'Field:max_wt_per_awb, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            29 => 'Field:max_vol_wt_per_awb, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            30 => 'Field:max_pc_per_awb, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            31 => 'Field:enable_api_link, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            32 => 'Field:api_base_url, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            33 => 'Field:api_username, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            34 => 'Field:api_password, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            35 => 'Field:api_service_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            36 => 'Field:tracking_days_in_website, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            37 => 'Field:fetch_zone_from_shipper, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            38 => 'Field:max_shipment_value, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            39 => 'Field:auth_letter_head, Type:int(2), Null:NO, Key:, Default:, Extra:',
            40 => 'Field:api_vendor_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            41 => 'Field:api_customer_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            42 => 'Field:check_max_shipment_in_docket, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',

            43 => 'Field:tracking_website, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            44 => 'Field:account_numbers, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            45 => 'Field:bluedart_product_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            46 => 'Field:fetch_zone_from_state, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            47 => 'Field:hide_forwarding_no_from_website, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            48 => 'Field:send_forwarding_no_2_in_website, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            49 => 'Field:dont_show_link_on_click, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            50 => 'Field:parcel_wise_discounted_ch_wt, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            51 => 'Field:send_forwarding_no_2_tracking_api, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            52 => 'Field:fetch_origin_zone_from_shipper_country, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            53 => 'Field:custom_invoice_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            54 => 'Field:tracking_url, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            55 => 'Field:chg_wt_per_item_pur, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            56 => 'Field:round_off_chg_wt_pur, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            57 => 'Field:api_company_id, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            58 => 'Field:is_house_mandatory, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            59 => 'Field:fetch_customer_ori_zone, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            60 => 'Field:fetch_customer_ori_zone_type, Type:tinyint(1), Null:NO, Key:, Default:, Extra:',
            61 => 'Field:fetch_vendor_ori_zone, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            62 => 'Field:fetch_vendor_ori_zone_type, Type:tinyint(1), Null:NO, Key:, Default:, Extra:',
            63 => 'Field:fetch_customer_dest_zone, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            64 => 'Field:fetch_customer_dest_zone_type, Type:tinyint(1), Null:NO, Key:, Default:, Extra:',
            65 => 'Field:fetch_vendor_dest_zone, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            66 => 'Field:fetch_vendor_dest_zone_type, Type:tinyint(1), Null:NO, Key:, Default:, Extra:',
            67 => 'Field:internal_api_service_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            68 => 'Field:enable_self_label_preview, Type:tinyint(1), Null:NO, Key:, Default:, Extra:',
            69 => 'Field:parcel_wise_discounted_ch_wt_purchase, Type:tinyint(1), Null:NO, Key:, Default:, Extra:',
            70 => 'Field:api_envelope_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            71 => 'Field:api_dox_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            72 => 'Field:api_nondox_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            73 => 'Field:max_vol_wt_per_pcs, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            74 => 'Field:curreny_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            75 => 'Field:sector_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            76 => 'Field:show_vendor_box_portal, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            77 => 'Field:show_shipper_copy_portal, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            78 => 'Field:single_pc_rate_wise_rate, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            79 => 'Field:cs_person_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            80 => 'Field:billing_person_id, Type:int(11), Null:NO, Key:, Default:, Extra:',
            81 => 'Field:min_wt_per_pc, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            82 => 'Field:min_vol_wt_per_pcs, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            83 => 'Field:min_wt_per_awb, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            84 => 'Field:min_vol_wt_per_awb, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            85 => 'Field:min_chargeable_wt_per_awb, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            86 => 'Field:mandate_hs_code_for_this_service, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            87 => 'Field:lane_wise_zone_mapping, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            88 => 'Field:max_chargeable_wt_per_awb, Type:decimal(20,2), Null:NO, Key:, Default:, Extra:',
            89 => 'Field:hide_pod_image_from_website, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            90 => 'Field:bluedart_sub_product_code, Type:varchar(255), Null:NO, Key:, Default:, Extra:',
            91 => 'Field:hide_pod_image_from_portal, Type:tinyint(1), Null:NO, Key:, Default:, Extra:',
            92 => 'Field:hide_this_service_in_portal, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',
            93 => 'Field:combine_lable_api, Type:tinyint(1), Null:NO, Key:, Default:2, Extra:',



        );
        return $column_structure;
    }
}
