<?php
$config['tracking_vendor'] = array(
    1 => array('name' => 'Fedex', 'label_key' => 'fedex', 'status' => '1', 'auth_required' => 2),
    2 => array('name' => 'dhl', 'label_key' => 'dhl', 'status' => '1', 'auth_required' => 2),
    3 => array('name' => 'aramex', 'label_key' => 'aramex', 'status' => '1', 'auth_required' => 2),
    4 => array('name' => 'linex', 'label_key' => 'linex', 'status' => '1', 'auth_required' => 2),
    5 => array('name' => 'ups', 'label_key' => 'ups', 'status' => '1', 'auth_required' => 2),
    6 => array('name' => 'awcc', 'label_key' => 'awcc', 'status' => '1', 'auth_required' => 2),
    7 => array('name' => 'airwings', 'label_key' => 'airwings', 'status' => '1', 'auth_required' => 2),
    8 => array('name' => 'bluedart', 'label_key' => 'bluedart', 'status' => '1', 'auth_required' => 2),
    9 => array('name' => 'dtdc', 'label_key' => 'dtdc', 'status' => '1', 'auth_required' => 2),
    10 => array('name' => 'tpcindia', 'label_key' => 'tpcindia', 'status' => '1', 'auth_required' => 2),
    11 => array('name' => 'overnite', 'label_key' => 'overnite', 'status' => '1', 'auth_required' => 2),
    12 => array('name' => 'trackon', 'label_key' => 'trackon', 'status' => '1', 'auth_required' => 2),
    13 => array('name' => 'accord global', 'label_key' => 'accord_global', 'status' => '1', 'auth_required' => 2),
    14 => array('name' => 'shreetirupati courier', 'label_key' => 'shreetirupaticourier', 'status' => '1', 'auth_required' => 2),
    15 => array('name' => 'shreenandan courier', 'label_key' => 'shreenandancourier', 'status' => '1', 'auth_required' => 2),
    16 => array('name' => 'skyking', 'label_key' => 'skyking', 'status' => '1', 'auth_required' => 2),
    17 => array('name' => 'madhur couriers', 'label_key' => 'madhurcouriers', 'status' => '1', 'auth_required' => 2),
    18 => array('name' => 'shreeanjani courier', 'label_key' => 'shreeanjanicourier', 'status' => '1', 'auth_required' => 2),
    19 => array('name' => 'speed post', 'label_key' => 'speed_post', 'status' => '1', 'auth_required' => 2),
    20 => array('name' => 'delhivery', 'label_key' => 'delhivery', 'status' => '1', 'auth_required' => 2),
    21 => array('name' => 'franch', 'label_key' => 'franch', 'status' => '1', 'auth_required' => 2),
    22 => array('name' => 'gati', 'label_key' => 'gati', 'status' => '1', 'auth_required' => 2),
    23 => array('name' => 'spoton', 'label_key' => 'spoton', 'status' => '1', 'auth_required' => 2),
    24 => array('name' => 'tpc', 'label_key' => 'tpc', 'status' => '1', 'auth_required' => 2),
    25 => array('name' => 'xpressbees', 'label_key' => 'xpressbees', 'status' => '1', 'auth_required' => 2),
    26 => array('name' => 'spicejet', 'label_key' => 'spicejet', 'status' => '1', 'auth_required' => 2),
    27 => array('name' => 'rivigo', 'label_key' => 'rivigo', 'status' => '1', 'auth_required' => 2),
    28 => array('name' => 'dpd', 'label_key' => 'dpd', 'status' => '1', 'auth_required' => 2),
    29 => array('name' => 'address india', 'label_key' => 'address_india', 'status' => '1', 'auth_required' => 2),
    30 => array('name' => 'skynet', 'label_key' => 'skynet', 'status' => '1', 'auth_required' => 2),
    31 => array('name' => 'safexpress', 'label_key' => 'safexpress', 'status' => '1', 'auth_required' => 2),
    32 => array('name' => 'parcelforce', 'label_key' => 'parcelforce', 'status' => '1', 'auth_required' => 2),
    33 => array('name' => 'ecom express', 'label_key' => 'ecomexpress', 'status' => '1', 'auth_required' => 2),
    34 => array('name' => 'first flight', 'label_key' => 'first_flight', 'status' => '1', 'auth_required' => 2),
    35 => array('name' => 'shree maruti cargo', 'label_key' => 'shree_maruti_cargo', 'status' => '1', 'auth_required' => 2),
    36 => array('name' => 'dtdc cargo', 'label_key' => 'dtdc_cargo', 'status' => '1', 'auth_required' => 2),
    37 => array('name' => 'tci', 'label_key' => 'tci', 'status' => '1', 'auth_required' => 2),
    38 => array('name' => 'dtdc courier', 'label_key' => 'dtdc_courier', 'status' => '1', 'auth_required' => 2),
    39 => array('name' => 'shree maruti courier', 'label_key' => 'shree_maruti_courier', 'status' => '1', 'auth_required' => 2),
    40 => array('name' => 'tnt', 'label_key' => 'tnt', 'status' => '1', 'auth_required' => 2),
);
$config['node_api_ip'] = 'http://139.59.43.12/';
$config['email_trigger'] = array(
    1 => array('id' => 1, 'config_key' => 'pod_email', 'config_value' => 'POD Email', 'field' => ''),
    2 => array('id' => 2, 'config_key' => 'weight_change_per_docket', 'config_value' => 'Weight Change Email Per Docket', 'field' => 'docket'),
    3 => array('id' => 3, 'config_key' => 'weight_change_daily', 'config_value' => 'Weight Change Email Daily', 'field' => ''),
    4 => array('id' => 4, 'config_key' => 'booking_email_per_docket', 'config_value' => 'Booking Email Per Docket', 'field' => 'docket'),
    5 => array('id' => 5, 'config_key' => 'booking_email_daily', 'config_value' => 'Booking Email Daily', 'field' => ''),
    6 => array('id' => 6, 'config_key' => 'customer_mis_email', 'config_value' => 'Customer MIS Email', 'field' => ''),
    7 => array('id' => 7, 'config_key' => 'vendor_mis_email', 'config_value' => 'Vendor MIS Email', 'field' => ''),
    8 => array('id' => 8, 'config_key' => 'customer_outstanding_email', 'config_value' => 'Customer Outstanding Email', 'field' => 'outstanding'),
    9 => array('id' => 9, 'config_key' => 'customer_invoice_email', 'config_value' => 'Customer Invoice Email', 'field' => 'invoice'),
);

$config['supported_label_vendor'] = array(
    1 => 'fedex',
    2 => 'dhl',
    3 => 'aramex',
    28 => 'dpd',
    41 => 'atlantic',
    8 => 'bluedart',
    23 => 'spoton',
    49 => 'fedex_deepblue',
    50 => 'delhivery_b2b',
    20 => 'delhivery',
    25 => 'xpressbees',
    9 => 'dtdc_intl',
    40 => 'tnt',
    51 => 'dhl_dxb',
    52 => 'fedex_dxb',
    53 => 'ups_standard_service',
    54 => 'ups_saver_service',
    55 => 'ups_expedited_service',
    57 => 'itd_self_service',
    58 => 'nimbuspost_domestic_service',
    59 => 'vendor',
    60 => 'ror_service',
    61 => 'bluedart_domestic',
    62 => 'south_africa_self',
    64 => 'post_plus',
    65 => 'smart_express',
    73 => 'pacific',
    74 => 'usps',
    75 => 'canada_post',
    76 => 'tdg',
    77 => 'fdl',
    78 => 'send_cloud',
    79 => 'fedex_us_ground',
    82 => 'nimbuspost',
    85 => 'delhivery_intl',
    83 => 'norsk',
    84 => 'xpression',
    94 => 'express_saver_service_ups',
    95 => 'eco_freight_ups',
    97 => 'ten',
    99 => 'my_express_hub',
    93 => 'ecom_api',
    103 => 'ekart',
    104 => 'speed_box',
    105 => 'movin',
    106 => 'yodel',
    110 => 'in_express',
    113 => 'dhl_usa',
    112 => 'fedex_import',
    114 => 'pikrr',
    116 => 'purolator',
);

$config['tracking_event_id'] = array(
    'entry' => 1,
    'pick_up_scan' => 2,
    'in_scan' => 3,
    'manifest' => 4,
    'remanifest' => 6,
    'incoming_manifest' => 5,
    'reincoming_manifest' => 5,
    'delivered' => 10,
    'in_transit' => 14,
    'undelivered' => 8,
    'rto' => 12,
    'misplaced' => 11,
    'cancel' => 13,
    'drs' => 7,
    'redrs' => 7,
);
$config['company_base_url'] = array(
    'test_company' => 'http://139.59.60.106/',
    'universal' => 'http://139.59.12.87/',
);

$config['super_admin'] = 14;
$config['billing_role'] = 2;
$config['director_role'] = 13;

$config["admin_role_name"] = array('software_user');
$config['auth_letter_head'] = array(
    array("id" => '1', "name" => 'fedex'),
    array("id" => '2', "name" => 'dhl'),
    array("id" => '3', "name" => 'ups'),
    array("id" => '4', "name" => 'tnt'),
    array("id" => '5', "name" => 'self'),
    array("id" => '6', "name" => 'self_import'),
    array("id" => '7', "name" => 'self_2'),
);

$config['multiple_login_id'] = array(
    '0' => "virag@itdservices.in",
);
